# Gitlab CI configuration
stages:
  - lint
  - test

# coverage before scripts
.lint-template: &lint-prepare
  image: node:7-alpine
  before_script:
    - apk --update add git
    - npm install
  tags:
    - alpine

# coverage before scripts
.coverage-template: &coverage-prepare
  image: node:7
  before_script:
    - wget -q -O - http://mozilla.debian.net/archive.asc | apt-key add -
    - echo "deb http://mozilla.debian.net/ jessie-backports firefox-beta" | tee -a /etc/apt/sources.list.d/mozilla-firefox.list
    - cp ./config/mozilla-firefox /etc/apt/preferences.d/mozilla-firefox
    - apt-get update
    - apt-cache policy firefox
    - apt-get install xvfb firefox -yqq
    - Xvfb :99 -ac &
    - export DISPLAY=:99
    - npm install
  tags:
    - ubuntu

coding-style:
  stage: lint
  <<: *lint-prepare
  script:
    - npm run lint

# Run tests and generate coverage report
test-and-coverage:
  stage: test
  <<: *coverage-prepare
  script:
    - npm run coverage
