verbose: false
instrumentation:
    extensions:
      - .js
    excludes:
      - 'config/*'
      - 'devel/*'
      - 'dist/*'
      - 'node_modules/*'
      - 'res/*'
      - 'tmp/*'
      - '**/lib/**'
      - '**/vendors/**'
    variable: __coverage__
    compact: true
    default-excludes: true
    preserve-comments: false
    save-baseline: false
    baseline-file: ./devel/coverage/coverage-baseline.raw.json
    include-all-sources: true
    es-modules: true
    auto-wrap: false
reporting:
    print: summary
    reports:
      - lcovonly
      - html
    dir: ./devel/coverage
    report-config:
        clover:
          file: clover.xml
        cobertura:
          file: cobertura-coverage.xml
        json:
          file: coverage-final.json
        json-summary:
          file: coverage-summary.json
        lcovonly:
          file: lcov.info
        teamcity:
          file: null
        text:
          file: null
        text-lcov:
          file: lcov.info
        text-summary:
          file: null
    watermarks:
        statements: [75, 90]
        lines: [75, 90]
        functions: [75, 90]
        branches: [75, 90]
hooks:
    hook-run-in-context: false
    post-require-hook: null
    handle-sigint: false
check:
    global:
        statements: 75
        lines: 75
        branches: 75
        functions: 75
        excludes: []
    each:
        statements: 50
        lines: 50
        branches: 50
        functions: 50
        excludes: []
